simulation:

  # file containing regions that are to be simulated using nanosim
  regions: "config/example_regions.tsv"

  # reference to be used for simulation
  reference: &ref
    name: "example_ref"
    path: "resources/example_ref.fasta"

  error_model:
    # construct nanosim error model from this sample
    nanopore:
      name: "sample"
      sample: "resources/sample.fastq.gz"
    # optional illumina reads
    #illumina:
    #  name: "illumina"
    #  sequencer: "HS20"
  # additional non-circular noise in the form of nanopore WGS reads which are added to circular reads above
  wgs_noise:
    coverage: 0.01
    
  # simulate regions at the given target coverages
  target_coverages: [1]  # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30, 40, 50]
