simulation:

  # file containing regions that are to be simulated using nanosim
  regions: "config/example_regions.tsv"

  reference: &ref
    name: "example_ref"
    path: "resources/example_ref.fasta"


  # construct nanosim error model from this sample
  error_model:
    name: "sample"
    sample: "resources/sample.fastq.gz"


  wgs_noise:
    coverage: 0.01
    
  # simulate regions at the given target coverages
  target_coverages: [1]  # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 30, 40, 50]
